ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/gpfs/home/egutierrez/.local/bin/pip'

Traceback (most recent call last):
  File "main.py", line 31, in <module>
    parameters = model_name_to_parameters(model_name)
  File "/gpfs/home/egutierrez/ddsp_textures/training/auxiliar.py", line 33, in model_name_to_parameters
    raise NameError("Invalid loss type")
NameError: Invalid loss type
